# This is a basic workflow to help you get started with Actions

name: cron_job

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    #- cron:  '00 10 * * *' #every day at 10 #when not in test mode
    - cron:  '*/40 * * * *'
   # Steps represent a sequence of tasks that will be executed as part of the job
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_cron_job.txt
      - name: Run daily_updates
        run: python cron_job_for_github.py 

