# This is a basic workflow to help you get started with Actions

name: cron_job

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '00 10 * * *' #every day at 10
   # Steps represent a sequence of tasks that will be executed as part of the job
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Run daily_updates
        run: daily_updates 

